name: Publish and Notify

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2

#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#
#      - name: Install dependencies
#        run: yarn install --frozen-lockfile
#
#      - name: Publish to npm
##        run: yarn publish --registry https://registry.npmjs.org/
#        run: echo "NPM_TOKEN is set!"
#        if: env.NODE_AUTH_TOKEN != ''
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Github Contexts Test
        run: |
          echo "REF_NAME ${github.ref_name} REF_TYPE ${github.ref_type} REPOSITORY ${github.repository}"

#      - name: Check TAG_NAME
#        run: echo ${{ steps.get_version.outputs.version }}

#      - uses: sarisia/actions-status-discord@v1
#        with:
#          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
#          nodetail: true
#          title: New version of `@zoop.studio/react-native-numberpad` is ready!
#          description: |
#            Version `${{ steps.get_version.outputs.version }}`
#            Click [${{ steps.get_version.outputs.version }}](https://github.com/zoop-studio/react-native-numberpad/tree/${{ steps.get_version.outputs.version }}) to download!
