name: Release

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup Node.js
#        uses: actions/setup-node@v2
#
#      - name: Install dependencies
#        run: yarn install --frozen-lockfile

#      - name: Publish to npm
##        run: yarn publish --registry https://registry.npmjs.org/
#        run: echo "NPM_TOKEN is set!"
#        if: env.NODE_AUTH_TOKEN != ''
#        env:
#          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

#      - name: Github Contexts Test
#        run: |
#          echo "REF_NAME: ${{ github.ref_name }}"
#          echo "REF_TYPE: ${{ github.ref_type }}"
#          echo "REPOSITORY: ${{ github.repository }}"

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Github Actions
          status: ${{ job.status }}
          title: `${{ github.ref_name }}`
          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          color: 0x006afe
