name: Pull Request for release

on:
  pull_request:
    branches:
      - 'main'

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  size-check:
    runs-on: ubuntu-latest
    needs: label
    permissions:
      pull-requests: write
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v2
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
