name: Pull Request for Release

on:
  pull_request:
    branches:
      - 'main'
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'release/')
    steps:
      - uses: actions/checkout@v3
      - run: yarn install --frozen-lockfile
      - run: yarn test

  label:
    runs-on: ubuntu-latest
    needs: test
    if: success()
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add label
        run: |
          gh pr edit ${{ github.event.pull_request.number }} --add-label release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  size-check:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      pull-requests: write
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v3
      - uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
