name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.ref }} == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: yarn publish
        if: env.NODE_AUTH_TOKEN != ''
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  notify:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: Github Actions
          status: ${{ job.status }}
          title: ${{ github.ref_name }}
          url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          color: 0x006afe
